### ISSUE TITLE
配置无能

### ISSUE THREAD

**Issue by funfunhey** [easychen/LazyRest4#1]
我把它放在本地根目录的lazyrest4文件中，然后各种报错，一点点改代码（好了，配到一半觉得太蠢了，路径太多改不了），尝试改htaccess文件
RewriteRule ^(.*)(css|js|gif|jpg|jpeg|txt|png)$  /lazyrest4/$1$2 
RewriteCond %{REQUEST_URI} !^/lazyrest4/
RewriteBase /lazyrest4
几款都试过了_(:зゝ∠)_
我可能比较智障，
很少配置htaccess，
认真求教（认真脸），
希望得到回复！thanks！

**Comment by ghost** [comment]
不是有文档么，按照文档来配置就没问题

**Comment by funfunhey** [comment]
其实应该就差一个路径问题而已，文档其他的应该都没问题了，不晓得要url重写还是apache那里要改路径，当然路径问题最简单就直接放在根目录下就好（然而我不想这么做啊），url重写好像没啥用，apache改httpd.conf那里改了一些（我也不造对不对），都没用才需要求助啊！！

**Comment by ghost** [comment]
作者已经把composer和bower配置好了，git clone后只要依次运行composer install --no-dev，cp sample.bowerrc .bowerrc，bower install，cp sample.htaccess .htaccess这几条命令就好

**Comment by willnewii** [comment]
你可以新添加一个虚拟目录直接指向lazyrest4.别把lazyrest4放在根目录下,再试试~

**Comment by funfunhey** [comment]
@willnewii  
另设了别名。。。进去后老是跳转到localhost/login 而不是localhost/lazya/login...（alias / 就根本没法用/(ㄒoㄒ)/~~，我是做错啥了）
Alias /lazya/ "F:/Program Files/wamp/www/lazyrest4/" 

<Directory "F:/Program Files/wamp/www/lazyrest4/">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride all
        Order allow,deny
    Allow from all
</Directory>

**Comment by easychen** [comment]
@funfunhey  目前只支持安装在web根目录。你可以配置一个域名，然后把document root设置在lazyrest的根。

**Comment by funfunhey** [comment]
@easychen  最后还是默默的改了document root了。。。我以为有法子可以两全其美的~~~弱弱问句linux就没那么麻烦吗
