### ISSUE TITLE
说明里的两个表的截图是同一个了。。。

### ISSUE THREAD

**Issue by ufoe** [easychen/LazyRest4#4]
直接放sql吧

CREATE TABLE IF NOT EXISTS `code` (
  `id` int(11) NOT NULL COMMENT '序号',
  `code` text NOT NULL COMMENT '代码',
  `name` varchar(64) NOT NULL COMMENT '名称',
  `uid` int(11) NOT NULL COMMENT '用户ID',
  `uname` varchar(32) NOT NULL COMMENT '用户名',
  `create_at` int(11) NOT NULL COMMENT '创建时间',
  `private` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否私有'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

---
## 
## -- 表的结构 `user`

CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL COMMENT '序号',
  `email` varchar(64) NOT NULL COMMENT '电子邮箱',
  `name` varchar(32) NOT NULL  COMMENT '名字',
  `password` varchar(32) NOT NULL  COMMENT '密码',
  `level` tinyint(4) NOT NULL DEFAULT '0'  COMMENT '级别'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
## 
## 
## -- Indexes for table `code`

ALTER TABLE `code`
  ADD PRIMARY KEY (`id`);
## 
## -- Indexes for table `user`

ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

**Comment by easychen** [comment]
已经更新了说明，感谢反馈 👍
